# Generated by Django 3.0.3 on 2020-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locus_name', models.CharField(blank=True, max_length=200)),
                ('TAIR_accession', models.CharField(blank=True, max_length=200)),
                ('object_name', models.CharField(blank=True, max_length=200)),
                ('relationship_type', models.CharField(blank=True, max_length=200)),
                ('GO_term', models.CharField(blank=True, max_length=200)),
                ('GO_ID', models.CharField(blank=True, max_length=200)),
                ('TAIR_Keyword_ID', models.CharField(blank=True, max_length=200)),
                ('Aspect', models.CharField(blank=True, max_length=200)),
                ('Goslim_term', models.CharField(blank=True, max_length=200)),
                ('Evidence_code', models.CharField(blank=True, max_length=200)),
                ('Evidence_description', models.CharField(blank=True, max_length=200)),
                ('Evidence_with', models.CharField(blank=True, max_length=200)),
                ('Reference', models.CharField(blank=True, max_length=200)),
                ('Annotator', models.CharField(blank=True, max_length=200)),
                ('Date_annotated', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'annotation',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.CreateModel(
            name='df_leaf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sym_Description', models.CharField(blank=True, max_length=200)),
                ('target_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'df_leaf',
            },
        ),
        migrations.CreateModel(
            name='df_root',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sym_Description', models.CharField(blank=True, max_length=200)),
                ('target_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'df_root',
            },
        ),
        migrations.CreateModel(
            name='df_shoot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sym_Description', models.CharField(blank=True, max_length=200)),
                ('target_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'df_shoot',
            },
        ),
        migrations.CreateModel(
            name='short_name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('FullName', models.CharField(blank=True, max_length=200)),
                ('Description_1', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'short_name',
            },
        ),
        migrations.CreateModel(
            name='tpm_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.CharField(blank=True, max_length=200)),
                ('Tpm', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'tpm_list',
            },
        ),
    ]
